import { useEffect, useState } from "react";
import { AlertCircle, Loader2, Plus, RefreshCw, Trash2, Upload } from "lucide-react";
import { api, ApiError, type CryptoPortfolioData, type CryptoPosition } from "@/lib/api";
import { GlassCard } from "@/components/ui/GlassCard";
import { portfolioNumber, portfolioSigned } from "@/lib/portfolio-format";
import { useLocale } from "@/lib/i18n";

export function CryptoPortfolioPanel() {
  const { tr } = useLocale();
  const [data, setData] = useState<CryptoPortfolioData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ wallet_label: "", asset: "", quantity: "", unit_cost: "", cost_currency: "USD" });
  const [csv, setCsv] = useState("");
  const [preview, setPreview] = useState<CryptoPosition[]>([]);
  const load = () => api.cryptoPortfolio("USD").then(setData).catch((reason) => setError(reason instanceof ApiError ? reason.message : tr("Unable to load crypto positions", "加密持仓加载失败")));
  useEffect(() => { void load(); }, []);
  const refresh = async () => { setLoading(true); setError(null); try { await api.refreshCryptoPositions(); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : tr("Coinbase refresh failed", "Coinbase 刷新失败")); } finally { setLoading(false); } };
  const add = async () => { const quantity = Number(form.quantity); if (!form.wallet_label.trim() || !form.asset.trim() || !Number.isFinite(quantity)) return; setLoading(true); setError(null); try { await api.upsertManualCrypto({ wallet_label: form.wallet_label, asset: form.asset, quantity, unit_cost: form.unit_cost ? Number(form.unit_cost) : null, cost_currency: form.cost_currency }); setForm({ wallet_label: "", asset: "", quantity: "", unit_cost: "", cost_currency: "USD" }); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : tr("Save failed", "保存失败")); } finally { setLoading(false); } };
  const remove = async (item: CryptoPosition) => { await api.removeManualCrypto(item.wallet_label, item.asset); await load(); };
  const previewCsv = async () => { try { setPreview((await api.previewCryptoCsv(csv)).rows); setError(null); } catch (reason) { setError(reason instanceof ApiError ? reason.message : tr("CSV validation failed", "CSV 校验失败")); } };
  const commitCsv = async () => { try { await api.importCryptoCsv(csv); setCsv(""); setPreview([]); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : tr("CSV import failed", "CSV 导入失败")); } };
  return <>
    <div className="mb-4 flex items-start gap-3 rounded-lg border border-success/25 bg-success/5 p-3"><div className="flex-1"><p className="text-sm font-semibold">{tr("Read-only Coinbase positions", "Coinbase 只读持仓")}</p><p className="text-xs text-muted-foreground">{tr("Credentials remain in backend environment variables; Vibe stores only normalized balance snapshots.", "凭据仅保存在后端环境变量；Vibe 只持久化规范化余额快照。")}</p></div><button onClick={refresh} disabled={loading} className="inline-flex items-center gap-1.5 rounded-lg bg-primary/15 px-3 py-2 text-xs text-primary">{loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}{tr("Sync Coinbase", "同步 Coinbase")}</button></div>
    {error && <p className="mb-4 flex items-center gap-2 rounded-lg border border-warning/30 bg-warning/5 p-3 text-sm text-warning"><AlertCircle className="h-4 w-4" />{error}</p>}
    {data && <div className="mb-4 grid grid-cols-2 gap-3 sm:grid-cols-3"><GlassCard className="p-3"><p className="text-xs text-muted-foreground">{tr("Crypto value", "加密市值")} · USD</p><p className="font-mono text-xl font-bold">{portfolioNumber(data.total)}</p></GlassCard><GlassCard className="p-3"><p className="text-xs text-muted-foreground">Cash-like crypto</p><p className="font-mono text-xl font-bold">{portfolioNumber(data.cash_like_total)}</p></GlassCard><GlassCard className="p-3"><p className="text-xs text-muted-foreground">{tr("Coinbase status", "Coinbase 状态")}</p><p className="text-lg font-bold">{data.coinbase.status}</p></GlassCard></div>}
    <GlassCard className="mb-4"><h3 className="mb-3 text-sm font-semibold">{tr("Add another wallet", "添加其他钱包持仓")}</h3><div className="flex flex-wrap items-end gap-2">{[
      ["wallet_label", tr("Wallet label", "钱包标签"), "Ledger"], ["asset", tr("Asset", "资产"), "BTC"], ["quantity", tr("Quantity", "数量"), "0.25"], ["unit_cost", tr("Unit cost (optional)", "单位成本（可选）"), "30000"], ["cost_currency", tr("Cost currency", "成本币种"), "USD"],
    ].map(([key, label, placeholder]) => <label key={key} className="text-xs text-muted-foreground"><span className="mb-1 block">{label}</span><input value={form[key as keyof typeof form]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} placeholder={placeholder} className="w-36 rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground" /></label>)}<button onClick={add} className="inline-flex items-center gap-1 rounded-lg bg-primary/15 px-3 py-2 text-sm text-primary"><Plus className="h-4 w-4" />{tr("Save", "保存")}</button></div></GlassCard>
    <GlassCard className="mb-4"><h3 className="mb-2 text-sm font-semibold">{tr("CSV import", "CSV 导入")}</h3><p className="mb-2 text-xs text-muted-foreground">{tr("Columns: wallet_label, asset, quantity, unit_cost, cost_currency. Validate the entire preview before committing atomically.", "列：wallet_label, asset, quantity, unit_cost, cost_currency。先完整校验预览，再原子提交。")}</p><input type="file" accept=".csv,text/csv" onChange={async (event) => { const file = event.target.files?.[0]; if (file) { setCsv(await file.text()); setPreview([]); } }} className="block text-xs text-muted-foreground" />{csv && <div className="mt-3 flex gap-2"><button onClick={previewCsv} className="inline-flex items-center gap-1 rounded border border-border px-3 py-1.5 text-xs"><Upload className="h-3.5 w-3.5" />{tr("Validate preview", "校验预览")}</button>{preview.length > 0 && <button onClick={commitCsv} className="rounded bg-primary/15 px-3 py-1.5 text-xs text-primary">{tr(`Import ${preview.length} rows`, `导入 ${preview.length} 行`)}</button>}</div>}{preview.length > 0 && <div className="mt-3 overflow-x-auto rounded-lg border border-border/60"><table className="w-full min-w-[620px] text-left text-xs"><thead className="bg-muted/30 text-muted-foreground"><tr>{[tr("Wallet", "钱包"), tr("Asset", "资产"), tr("Quantity", "数量"), tr("Unit cost", "单位成本"), tr("Cost currency", "成本币种")].map((label) => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{preview.map((item) => <tr key={`${item.wallet_label}-${item.asset}`} className="border-t border-border/40"><td className="p-2">{item.wallet_label}</td><td className="p-2 font-mono font-semibold">{item.asset}</td><td className="p-2 font-mono">{portfolioNumber(item.quantity)}</td><td className="p-2 font-mono">{item.unit_cost == null ? "—" : portfolioNumber(item.unit_cost)}</td><td className="p-2">{item.cost_currency || "USD"}</td></tr>)}</tbody></table></div>}</GlassCard>
    <GlassCard className="mb-4"><h3 className="mb-3 text-sm font-semibold">{tr("Summary by asset", "按资产汇总")}</h3>{!data?.assets.length ? <p className="text-sm text-muted-foreground">{tr("No positions.", "暂无持仓。")}</p> : <div className="grid gap-2 sm:grid-cols-2">{data.assets.map((item) => <div key={item.asset} className="rounded-lg bg-muted/25 p-3"><div className="flex items-center justify-between"><span className="font-mono font-semibold">{item.asset}{item.cash_like ? <span className="ml-1 text-[9px] text-emerald-400">cash-like</span> : null}</span><span className="font-mono">{portfolioNumber(item.reporting_market_value)} {item.reporting_currency}</span></div><p className="mt-1 text-xs text-muted-foreground">{tr("Quantity", "数量")} {portfolioNumber(item.quantity)} · {item.sources.map((source) => source.wallet_label).join(" / ")}</p></div>)}</div>}</GlassCard>
    <GlassCard><h3 className="mb-3 text-sm font-semibold">{tr("Source details", "来源明细")}</h3>{!data?.positions.length ? <p className="py-6 text-center text-sm text-muted-foreground">{tr("No positions. Configure a Coinbase view key or add another wallet.", "暂无持仓。配置 Coinbase view key 或添加其他钱包。")}</p> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead><tr className="border-b border-border/50 text-left text-muted-foreground">{[tr("Source", "来源"), tr("Asset", "资产"), tr("Quantity", "数量"), tr("Price", "价格"), tr("Market value", "市值"), tr("Cost / P&L", "成本 / P&L"), ""].map((value) => <th key={value} className="p-2">{value}</th>)}</tr></thead><tbody>{data.positions.map((item, index) => <tr key={`${item.source}-${item.wallet_label}-${item.asset}-${index}`} className="border-b border-border/30"><td className="p-2">{item.wallet_label}</td><td className="p-2 font-mono font-semibold">{item.asset}{item.cash_like ? <span className="ml-1 rounded bg-emerald-500/10 px-1 text-[9px] text-emerald-400">cash-like</span> : null}</td><td className="p-2 font-mono">{portfolioNumber(item.quantity)}</td><td className="p-2 font-mono">{portfolioNumber(item.price)} {item.price_currency}</td><td className="p-2 font-mono">{portfolioNumber(item.reporting_market_value)} {item.reporting_currency}</td><td className="p-2 font-mono">{item.cost_value == null ? tr("Not provided", "未提供") : `${portfolioNumber(item.cost_value)} / ${portfolioSigned(item.pnl)}`}</td><td className="p-2">{item.source === "manual" && <button onClick={() => remove(item)} className="text-muted-foreground hover:text-destructive" title={tr("Delete", "删除")}><Trash2 className="h-3.5 w-3.5" /></button>}</td></tr>)}</tbody></table></div>}{data?.gaps.length ? <p className="mt-3 text-xs text-warning">{tr("Data gaps", "数据缺口")}：{data.gaps.join("；")}</p> : null}</GlassCard>
  </>;
}
